import Link from 'next/link';

export default async function JournalPost({ params }: { params: Promise<{ slug: string }> }) {
  const resolvedParams = await params;
  const getPost = (slug: string) => {
    switch (slug) {
      case 'the-story-of-the-baiji':
        return {
          title: 'EDITION NO. 01 — THE BAIJI',
          date: 'Aug 14, 2026',
          subtitle: 'Lipotes vexillifer, declared functionally extinct, 2006',
          content: [
            "For roughly 20 million years, the baiji swam the Yangtze — a pale, near-blind river dolphin that navigated its murky home almost entirely by sound. It is a possibly extinct species of river dolphin native to the Yangtze river system in China, thought to be the first dolphin species driven to extinction by human activity. In China it carried a gentler name: the \"Goddess of Chang Jiang,\" believed by many to have existed for several million years.",
            "The decline was fast, even by the standards of extinction. Before 1950 there were an estimated 6,000 baiji; by the 1980s only around 300 remained. By 1997 a survey found just 13 left, making it the most critically endangered dolphin on Earth. The causes weren't a single event but an accumulation: overfishing that depleted the fish the baiji depended on, destructive fishing methods like electrofishing and gill nets, and a sharp rise in ship traffic on one of the world's busiest rivers. Electric fishing nets alone were estimated to have killed 40% of the baiji population during the 1990s, though starvation from overfishing was the deeper cause, especially for young dolphins learning to catch fish on their own.",
            "img:/images/baiji-2.jpg",
            "The Yangtze basin is home to roughly 12% of the world's human population, and the rapid economic development along its banks degraded the habitat faster than the species could adapt. The Three Gorges Dam is often cited as the final blow to an ecosystem already pushed past its limit.",
            "img:/images/baiji-3.jpg",
            "In late 2006, a six-week international expedition surveyed the length of the river. No baiji were detected, and on December 13, 2006, expedition leaders declared the species \"functionally extinct.\" It was formally declared extinct the following year, marking the first extinction of a large aquatic mammal in roughly fifty years — and the loss of an entire ancient family of dolphin, Lipotidae, that the baiji alone represented.",
            "One baiji, a male named Qi Qi, had been rescued by fishermen in 1980 and lived at the Institute of Hydrobiology in Wuhan. He survived in captivity for 22 years, until his death in 2002. He remains the last baiji anyone touched, measured, or truly knew.",
            "Edition No. 01 is numbered 1–200. Each pair carries the mark of an animal that outlasted twenty million years of the natural world, and fewer than fifty of ours."
          ]
        };
      case 'why-we-stamp-every-pair':
        return {
          title: 'WHY WE HAND-STAMP EVERY PIECE',
          date: 'Jul 28, 2026',
          content: [
            "Every Vanara piece leaves the workshop carrying a number, pressed by hand onto the inside label — not printed, not lasered, not generated by a machine that repeats the same motion a thousand times a day. A person holds the stamp, aligns it, and presses down once. It will never be pressed in quite that way again.",
            "We do this because mass production solves for consistency, and consistency is the opposite of what we're trying to make. A factory line exists to remove variation — every unit identical, every flaw engineered out. That's the right goal for most things people buy. It's the wrong goal for something meant to mark a loss that can't be repeated.",
            "The hand-stamp is slower. It's less efficient. Some numbers sit slightly off-center; the pressure varies piece to piece. We don't correct for that — we leave it. A number stamped by a human hand carries the small, unrepeatable imperfections of the hand that stamped it, which feels like the only honest way to mark something that claims to be one of one.",
            "When your piece arrives, check the inside label — the number there isn't a SKU. It's a record of a single moment where someone pressed it into the fabric and moved on to the next, until 200 became zero, and the run closed for good."
          ]
        };
      case 'sustainable-materials':
        return {
          title: 'OUR MATERIAL PHILOSOPHY',
          date: 'Date pending',
          content: [
            "A limited-edition sweatshirt that claims to honor a lost species and then gets built from thin, mass-market fleece would be a contradiction we're not willing to live with. So the materials matter as much as the story.",
            "Every Vanara piece starts with 100% super combed cotton, woven at 300–350 GSM as a heavyweight French terry — dense enough to hold its shape for years, with soft inner loops that keep it comfortable for all-day wear rather than something you take off after an hour. The fabric is pre-shrunk before cutting, so the fit you buy is the fit that lasts, not one that changes shape after the first wash.",
            "Every logo is embroidered, not printed — a raised, textured mark that ages the way stitching does rather than the way screen-print cracks and fades. It's a small decision, but it's the same instinct behind everything we make: choose the version that holds up, even if it costs more to produce.",
            "We work with factories we can name, whose labor practices we can describe in specifics rather than vague reassurances — fair wages, safe conditions, and long-term relationships rather than the lowest bid each season. If we can't stand behind how something was made, we don't put our name on it.",
            "None of this makes a sweatshirt carbon-neutral or perfect — no supply chain is. But it means the choices behind each Edition are ones we're willing to have questioned, in detail, by anyone who asks."
          ]
        };
      default:
        return null;
    }
  };

  const post = getPost(resolvedParams.slug);

  if (!post) {
    return (
      <main className="va-view active" style={{ minHeight: '80vh', padding: '10vh 6vw', textAlign: 'center' }}>
        <h1 className="serif" style={{ fontSize: '32px', color: 'var(--brick)' }}>Record Not Found</h1>
        <Link href="/journal" className="va-btn" style={{ marginTop: '24px', display: 'inline-block' }}>Return to Journal</Link>
      </main>
    );
  }

  return (
    <main className="va-view active" style={{ minHeight: '80vh', padding: '10vh 6vw' }}>
      <div style={{ maxWidth: '720px', margin: '0 auto' }}>
        <Link href="/journal" style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: '11px', color: 'var(--bone-dim)', textTransform: 'uppercase', letterSpacing: '0.05em', textDecoration: 'none', display: 'inline-block', margin: '0 0 40px 0' }}>
          &larr; Back to Notes
        </Link>
        <div style={{ fontFamily: "'IBM Plex Mono', monospace", fontSize: '11px', color: 'var(--river)', marginBottom: '16px' }}>
          {post.date}
        </div>
        <h1 className="serif" style={{ fontSize: 'clamp(32px, 5vw, 48px)', marginBottom: post.subtitle ? '12px' : '40px', lineHeight: '1.2' }}>{post.title}</h1>
        
        {post.subtitle && (
          <div style={{ fontSize: '15px', fontStyle: 'italic', color: 'var(--bone-dim)', marginBottom: '40px' }}>
            {post.subtitle}
          </div>
        )}

        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          {post.content.map((paragraph, idx) => {
            if (paragraph.startsWith('img:')) {
              return (
                <img 
                  key={idx} 
                  src={paragraph.replace('img:', '')} 
                  alt={`${post.title} image`} 
                  style={{ width: '100%', borderRadius: '8px', marginTop: '16px', marginBottom: '16px', objectFit: 'cover' }} 
                />
              );
            }
            return (
              <p key={idx} style={{ color: 'var(--bone-dim)', fontSize: '16px', lineHeight: '1.8' }}>
                {paragraph}
              </p>
            );
          })}
        </div>
      </div>
    </main>
  );
}
